language: go
go:
- 1.8
- tip
script:
- go test -v *.go
- go build -o downloadcounter ./bin/*.go
deploy:
  provider: releases
  api_key:
    secure: SU7hVJR7/o18sUjM+KhUtX0yjSJ4HkTyeII6r7G4CmfXmL+gSrM0prOi5t4MdPUD96QnTFZYfbt5yYDivp59a4J5lkaAkZH2QSPcPYfOUK7UTq42JXxN82yn/EW4MdhlzCQAhSG5kFFcPudcSjWdyKaib9DjqiG73yltxJN7YI63JwtLHEdxRKcfy3wW9n1KIt1sPwI1Y+3EICHr1wASm5NbZcfS++hingtKkrg1b7/+GstT1CBsRJfbIYWzeA9ChgsviXISZfWMLqLI8y/kyzpVZjP1NZnpH7lOHLemAcfmNdvRrBEMw52F4UxcHGOyc4lmXL0Ay53U2Qgdw67qs0LOL5qaNiBbjEaJmhaHLTDftAjLkWZVLAsA9eH1WBt+JUy8h2XFC8HrBvxLc759kv95EqyHVYN7S1Xk+Ov7RBCP5EYHmRKIWENIk25JHaXUMreAV1ku6q5MSkhSLlJGWM5etS4oUrRY1M2f9snf8ooo4Uxp+KkNiW4R40iW4+5oKfJ0sZpg5Cee9uDoBo1MRsbu+k3XskpjcICMXCflMPoR6Nr1XHNW+EBxuK+xubZT/jWPKHhwdmzzKgSzSr9qdwzxdjD6RnR0c88zBJQYt99esEz/UkSpPs+/NWgRCpALNJf8+u+duw8MwhnoQ2ktVeiB675eECTPwYCuVgukppU=
  file: downloadcounter
  on:
    tags: true
